apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bio-rag

resources:
  - namespace.yaml
  - backend-deployment.yaml
  - frontend-deployment.yaml
  - worker-deployment.yaml
  - ingress.yaml
  - hpa.yaml

commonLabels:
  app: bio-rag
  managed-by: kustomize
